### ISSUE TITLE
TSV Support for Timecode+

### ISSUE THREAD

**Issue by pulpjedi** [latenitefilms/MarkerToolbox#14]
Timecode+ is an iOS app we use to make time coded notes during production. It only exports to TSV. I’ve attached two samples of TSV files from my actual interviews—one long, and one short.

I don’t see how to attach files, so here is a download link:
https://www.icloud.com/iclouddrive/05f-_k2T1lVoH5-UxFxcZjGKw#Timecode+_Notes

Thank you for your hard work!

**Comment by latenitefilms** [comment]
This will be added in v1.3.0.

**Comment by pulpjedi** [comment]
Hey Chris,

Happy new year! You probably saw this already but I thought I would follow up to be thorough. I filed a bug report on GitHub about a new Marker Toolbox bug that seems to have started with Final Cut Pro 11.

https://github.com/latenitefilms/MarkerToolbox/issues/38

Thanks for the hard work!

Jeff Roy
