### ISSUE TITLE
Vimeo is outputting CSV files with too many quotes

### ISSUE THREAD

**Issue by YevantZ** [latenitefilms/MarkerToolbox#31]
I possess a CSV file from Vimeo, but it's only covering a 2-minute duration in the Final Cut Pro timeline. Assistance is needed, please.
[review_notes_880909397.csv](https://github.com/latenitefilms/MarkerToolbox/files/14915091/review_notes_880909397.csv)

**Comment by latenitefilms** [comment]
I believe this is the same issue as #30 - Vimeo recently started outputting CSV files with too many quotes.

Try this file:
[review_notes_880909397_fixed.csv](https://github.com/latenitefilms/MarkerToolbox/files/14915676/review_notes_880909397_fixed.csv)

**Comment by latenitefilms** [comment]
Closing in favour of #30

**Comment by latenitefilms** [comment]
This has been fixed in Marker Toolbox v1.3.1. Thanks for reporting!
