### ISSUE TITLE
Process Comments Locally Export Broken in v1.4.0

### ISSUE THREAD

**Issue by KenHell** [latenitefilms/MarkerToolbox#35]
I'll attach a screenshot to illustrate that all looks well: I've pasted some comments from an email, processed locally, and it all looks good to go. When I hit Save File, the Avid marker .txt is completely empty, and the Resolve EDL simply has "TITLE: Marker Toolbox
FCM: NON-DROP FRAME".
![Screenshot 2024-08-12 at 17 50 54](https://github.com/user-attachments/assets/93f3d16f-9ba4-44ff-b5a1-9c7838cf599a)

Apologies if I'm just missing a step or doing something else wrong.

All best,
Kenny Park.

**Comment by latenitefilms** [comment]
Sorry you're having issues!

That's weird! Are you able to share the text that's doing this? I wonder if it's the dashes (`-`) that's breaking things?

**Comment by latenitefilms** [comment]
I've been able to track down the issue. APOLOGIES! 

Will try and push out a fix ASAP.

**Comment by latenitefilms** [comment]
This should be fixed in v1.4.1 soon!

**Comment by latenitefilms** [comment]
V1.4.1 is out now on the Mac App Store - let me know if that fixes your issues. Fingers crossed!

**Comment by KenHell** [comment]
Hi, Chris.

That works perfectly now. Many thanks!


All best,
Kenny.
